baseurl = "https://bretcrownacademy.netlify.app/"
description = ""
enableGitInfo = true
enableRobotsTXT = true
paginate = 9
title = "Bretcrown Academy"
[blackfriday]
fractions = false
[markup.goldmark.renderer]
unsafe = true
[params]
author = "Bretcrownoil"
coursePrice = "1995.00"
email = "admin@bretcrown.com"
ga_analytics = "UA-156539904-2"
ga_verify = "ZaNNn0hSVhEblnb4DBJ2Fvx6ZH3Baoa6zSkGmFkDqrU"
image = ""
logo = "academia.png"
paypalClient = "ASt9D7H91sMv8Y3iM2s_w5jaBkdlBxDd3Pn-ylG2HjHtvVxtlYtSuYbXfZgVTSr0rdquXO_QoSK0rxXl"
url = "https://bretcrownacademy.com"
[params.success]
description = "Your payment to Bretcrown Trading Academy has been received."
heading = "Thank you,"
[taxonomies]
tag = "tags"
